spring.application.name=juguetes-reservas-api
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/juguetes_reservas
spring.datasource.username=postgres
spring.datasource.password=higosfritos99

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Otras opciones
spring.jpa.properties.hibernate.format_sql=true
