spring.application.name=juguetes-reservas-api
# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d1d86aqli9vc73a91f20-a:5432/juguetesdb
spring.datasource.username=juguetesdb_user
spring.datasource.password=NNzkFVZif49nGxfhbYjO5dB3mRz3hGgR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

# Otras opciones
spring.jpa.properties.hibernate.format_sql=true
